### ISSUE TITLE
Permit denied

### ISSUE THREAD

**Issue by daviddias** [jbenet/asciinema-selfhost#2]
I'm getting a:

```
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>E4A0DCFA0825598A</RequestId><HostId>RZPtHH3avhhN/wbzE0iKvafXkaBD1WMlDiAkCUgi1Yk3cgErwxyr/7WCZMFd59cSiqlNdOR4yO0=</HostId></Error>
```

On the response body when fetching the asciinema to rehost.

![image](https://cloud.githubusercontent.com/assets/1211152/22820067/10f44b30-ef2a-11e6-80a4-a75e2499be59.png)

**Comment by daviddias** [comment]
Absolutely, here you go:

```
 ~/code ⮀
» asciinema-selfhost --rehost 773gpqt90qnvvnti678pj5wex
cloning 773gpqt90qnvvnti678pj5wex to /tmp/asciinema/773gpqt90qnvvnti678pj5wex
copying /usr/local/lib/node_modules/asciinema-selfhost/build to /tmp/asciinema/773gpqt90qnvvnti678pj5wex
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>E4A0DCFA0825598A</RequestId><HostId>RZPtHH3avhhN/wbzE0iKvafXkaBD1WMlDiAkCUgi1Yk3cgErwxyr/7WCZMFd59cSiqlNdOR4yO0=</HostId></Error>
undefined:1
<?xml version="1.0" encoding="UTF-8"?>
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/asciinema-selfhost/index.js:38:21)
    at Request.self.callback (/usr/local/lib/node_modules/asciinema-selfhost/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/asciinema-selfhost/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/asciinema-selfhost/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
```

**Comment by jbenet** [comment]
Ok bare requests no longer have permission to take the asciinema. or maybe the URL changed.

hey @sickill -- is it ok still to grab asciinemas and self-host them? if so, how should we do it now? or how should we do this? maybe asciinema tooling has evolved to no longer need this module.

**Comment by ku1ik** [comment]
@jbenet yes, it should still be working. Just append `.json` to any recording URL and you will get the recoding JSON.

The player is a standalone project now, and you can very easily self-host: https://github.com/asciinema/asciinema-player#download-the-player

So you basically need to:
* fetch https://github.com/asciinema/asciinema-player/releases/download/v2.4.0/asciinema-player.js
* fetch https://github.com/asciinema/asciinema-player/releases/download/v2.4.0/asciinema-player.css
* fetch the recording, for ex. https://asciinema.org/a/28307.json
* generate static html file (as shown in the linked README section)

**Comment by jbenet** [comment]
@sickill is it possible for the recorder to output the json locally, without touching asciinema.org?  (offline use)

**Comment by jbenet** [comment]
Answered my own question: https://github.com/asciinema/asciinema#rec-filename i see this now, that's fantastic, thanks @sickill (i thought i had seen this before, glad it was the case)

@whyrusleeping @diasdavid take a look at https://github.com/asciinema/asciinema#rec-filename -- this module (asciinema-selfhost) is mostly obviated now. do we even need it?

**Comment by jbenet** [comment]
@diasdavid @whyrusleeping this module has been updated and works again now. use https://github.com/jbenet/asciinema-selfhost#self-hosting

thanks very much @sickill -- asciinema is great! :) -- we will be using it a lot for examples soon. <3

**Comment by daviddias** [comment]
thank you  :D

**Comment by ku1ik** [comment]
@jbenet awesome!
